package gnf.gido.administracion.entities;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MorososNisId generated by hbm2java
 */
@Embeddable
 
// Begin-NamedQuery (NO REMOVE)

// End-NamedQuery (NO REMOVE)

public class MorososNisId  implements java.io.Serializable {
	 
	private static final long serialVersionUID = 1L;

	private int nisRad;
	
	private String estDeuda;
	
	
    public MorososNisId() {
    
    }	   
   
            
                @Column(name="NIS_RAD", nullable=false, precision=7, scale=0)
    public int getNisRad() {
            return this.nisRad;
    }
    
    public void setNisRad(int nisRad) {
        this.nisRad = nisRad;
    }
   
            
                @Column(name="EST_DEUDA", nullable=false, length=5)
    public String getEstDeuda() {
            return this.estDeuda;
    }
    
    public void setEstDeuda(String estDeuda) {
        this.estDeuda = estDeuda;
    }
	
	
	public boolean equals(Object other) { 
		if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof MorososNisId) ) return false;
		MorososNisId castOther = ( MorososNisId ) other;
		return (this.getNisRad()==castOther.getNisRad())
 && ( (this.getEstDeuda()==castOther.getEstDeuda()) || ( this.getEstDeuda()!=null && castOther.getEstDeuda()!=null && this.getEstDeuda().equals(castOther.getEstDeuda()) ) );
	}
	
	public int hashCode() {
		int result = 31;
		result = 37 * result + this.getNisRad();
		result = 37 * result + ( getEstDeuda() == null ? 0 : this.getEstDeuda().hashCode() );
		return result;
	}
		
		
	
 }

