package gnf.gido.administracion.entities;


import gnf.ada.core.persistence.AbstractEntity;
import java.math.BigDecimal;
import java.sql.Timestamp;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * MorososNis generated by hbm2java
 */
@Entity
@Table(name="GID_MOROSOS_NIS"
)
 
// Begin-NamedQuery (NO REMOVE)

// End-NamedQuery (NO REMOVE)

public class MorososNis  extends AbstractEntity  implements java.io.Serializable {
	 
	private static final long serialVersionUID = 1L;

	private MorososNisId id;
	
	private Byte optimistLock;
	
	private long nic;
	
	private BigDecimal deuda;
	
	private long facturas;
	
	private Timestamp fVencimiento;
	
	
    public MorososNis() {
    
    }	   
   
		        @javax.persistence.EmbeddedId

                
                @AttributeOverrides( {
        @AttributeOverride(name="nisRad", column=@Column(name="NIS_RAD", nullable=false, precision=7, scale=0) ), 
        @AttributeOverride(name="estDeuda", column=@Column(name="EST_DEUDA", nullable=false, length=5) ) } )
    public MorososNisId getId() {
            return this.id;
    }
    
    public void setId(MorososNisId id) {
        this.id = id;
    }
   
            
	@Version
	@org.hibernate.annotations.Type(type = "gnf.ada.core.persistence.hibernate.types.VersionByteType")
                @Column(name="OPTIMIST_LOCK", precision=2, scale=0)
    public Byte getOptimistLock() {
            return this.optimistLock;
    }
    
    public void setOptimistLock(Byte optimistLock) {
        this.optimistLock = optimistLock;
    }
   
                
                @Column(name="NIC", nullable=false, precision=7, scale=0)
    public long getNic() {
            return this.nic;
    }
    
    public void setNic(long nic) {
        this.nic = nic;
    }
   
                
                @Column(name="DEUDA", nullable=false, precision=20, scale=0)
    public BigDecimal getDeuda() {
            return this.deuda;
    }
    
    public void setDeuda(BigDecimal deuda) {
        this.deuda = deuda;
    }
   
                
                @Column(name="FACTURAS", nullable=false, precision=10, scale=0)
    public long getFacturas() {
            return this.facturas;
    }
    
    public void setFacturas(long facturas) {
        this.facturas = facturas;
    }
   
             
                @Column(name="F_VENCIMIENTO", nullable=false, length=7)
//                @Temporal(TemporalType.DATE)
    public Timestamp getFVencimiento() {
            return this.fVencimiento;
    }
    
    public void setFVencimiento(Timestamp FVencimiento) {
        this.fVencimiento = FVencimiento;
    }
	
	
	
	/**
	 * Metodo para obtener el tipo de la clase
	 */
	@Override
	@javax.persistence.Transient
	public Class<?> getClase(){
		return MorososNis.class;
	}
	
	public boolean equals(Object other) {
		if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof MorososNis) ) return false;
		MorososNis castOther = (MorososNis) other;
		if (getId() == null) {
			if (castOther.getId() != null) return false;
		}
		return this.getId().equals(castOther.getId());
	}
	
	public int hashCode() {
		return getId().hashCode();
	}    
		
		
	
 }

