package gnf.gido.administracion.entities;


import gnf.ada.core.persistence.AbstractEntity;
import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Universo generated by hbm2java
 */
@Entity
@Table(name="GID_UNIVERSOS"
    , uniqueConstraints = @UniqueConstraint(columnNames="NOMBRE") 
)
 
// Begin-NamedQuery (NO REMOVE)

// End-NamedQuery (NO REMOVE)

public class Universo  extends AbstractEntity  implements java.io.Serializable {
	 
	private static final long serialVersionUID = 1L;

	private int iduniverso;
	
	private Byte optimistLock;
	
	private String nombre;
	
	private String descripcion;
	
	private String tipCreacion;
	
	private Timestamp fCreacion;
	
	private Timestamp fModificacion;
	
	private byte estado;
	
	private boolean uIddelegacion;
	
	private short uCodUnicom;
	
	private short uCodProv;
	
	private int uCodDepto;
	
	private long uCodLocal;
	
	private long uCodBarrio;
	
	private String tTipServ;
	
	private String tTipCli;
	
	private String tTipMerc;
	
	private String tTipNatur;
	
	private byte tCortable;
	
	private String tMedido;
	
	private String tTipMedidor;
	
	private String tTipCiiu;
	
	private String dEstSum;
	
	private String dEstContrato;
	
	private String dTarifa;
	
	private byte dCalificacion;
	
	private short dRuta;
	
	private String dMarcMedidor;
	
	private byte dMultifamiliar;
	
	private byte dGestor;
	
	
    public Universo() {
    
    }	   
   
		        @javax.persistence.Id
	@javax.persistence.GeneratedValue(generator="nameGenerator")
	@javax.persistence.SequenceGenerator(name="nameGenerator",sequenceName="SEC_UNIVERSOS",allocationSize=1)
                
                @Column(name="IDUNIVERSO", unique=true, nullable=false, precision=8, scale=0)
    public int getIduniverso() {
            return this.iduniverso;
    }
    
    public void setIduniverso(int iduniverso) {
        this.iduniverso = iduniverso;
    }
    
	@javax.persistence.Transient
	public Object getId() {
		return this.iduniverso;
	}
   
            
	@Version
	@org.hibernate.annotations.Type(type = "gnf.ada.core.persistence.hibernate.types.VersionByteType")
                @Column(name="OPTIMIST_LOCK", precision=2, scale=0)
    public Byte getOptimistLock() {
            return this.optimistLock;
    }
    
    public void setOptimistLock(Byte optimistLock) {
        this.optimistLock = optimistLock;
    }
   
                
                @Column(name="NOMBRE", unique=true, nullable=false, length=30)
    public String getNombre() {
            return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
   
                
                @Column(name="DESCRIPCION", length=200)
    public String getDescripcion() {
            return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
   
                
                @Column(name="TIP_CREACION", nullable=false, length=5)
    public String getTipCreacion() {
            return this.tipCreacion;
    }
    
    public void setTipCreacion(String tipCreacion) {
        this.tipCreacion = tipCreacion;
    }
   
             
                @Column(name="F_CREACION", nullable=false, length=7)
//                @Temporal(TemporalType.DATE)
    public Timestamp getFCreacion() {
            return this.fCreacion;
    }
    
    public void setFCreacion(Timestamp FCreacion) {
        this.fCreacion = FCreacion;
    }
   
             
                @Column(name="F_MODIFICACION", nullable=false, length=7)
//                @Temporal(TemporalType.DATE)
    public Timestamp getFModificacion() {
            return this.fModificacion;
    }
    
    public void setFModificacion(Timestamp FModificacion) {
        this.fModificacion = FModificacion;
    }
   
                
                @Column(name="ESTADO", nullable=false, precision=2, scale=0)
    public byte getEstado() {
            return this.estado;
    }
    
    public void setEstado(byte estado) {
        this.estado = estado;
    }
   
                
                @Column(name="U_IDDELEGACION", nullable=false, precision=1, scale=0)
    public boolean isUIddelegacion() {
            return this.uIddelegacion;
    }
    
    public void setUIddelegacion(boolean UIddelegacion) {
        this.uIddelegacion = UIddelegacion;
    }
   
                
                @Column(name="U_COD_UNICOM", nullable=false, precision=4, scale=0)
    public short getUCodUnicom() {
            return this.uCodUnicom;
    }
    
    public void setUCodUnicom(short UCodUnicom) {
        this.uCodUnicom = UCodUnicom;
    }
   
                
                @Column(name="U_COD_PROV", nullable=false, precision=4, scale=0)
    public short getUCodProv() {
            return this.uCodProv;
    }
    
    public void setUCodProv(short UCodProv) {
        this.uCodProv = UCodProv;
    }
   
                
                @Column(name="U_COD_DEPTO", nullable=false, precision=9, scale=0)
    public int getUCodDepto() {
            return this.uCodDepto;
    }
    
    public void setUCodDepto(int UCodDepto) {
        this.uCodDepto = UCodDepto;
    }
   
                
                @Column(name="U_COD_LOCAL", nullable=false, precision=10, scale=0)
    public long getUCodLocal() {
            return this.uCodLocal;
    }
    
    public void setUCodLocal(long UCodLocal) {
        this.uCodLocal = UCodLocal;
    }
   
                
                @Column(name="U_COD_BARRIO", nullable=false, precision=10, scale=0)
    public long getUCodBarrio() {
            return this.uCodBarrio;
    }
    
    public void setUCodBarrio(long UCodBarrio) {
        this.uCodBarrio = UCodBarrio;
    }
   
                
                @Column(name="T_TIP_SERV", nullable=false, length=5)
    public String getTTipServ() {
            return this.tTipServ;
    }
    
    public void setTTipServ(String TTipServ) {
        this.tTipServ = TTipServ;
    }
   
                
                @Column(name="T_TIP_CLI", nullable=false, length=5)
    public String getTTipCli() {
            return this.tTipCli;
    }
    
    public void setTTipCli(String TTipCli) {
        this.tTipCli = TTipCli;
    }
   
                
                @Column(name="T_TIP_MERC", nullable=false, length=5)
    public String getTTipMerc() {
            return this.tTipMerc;
    }
    
    public void setTTipMerc(String TTipMerc) {
        this.tTipMerc = TTipMerc;
    }
   
                
                @Column(name="T_TIP_NATUR", nullable=false, length=5)
    public String getTTipNatur() {
            return this.tTipNatur;
    }
    
    public void setTTipNatur(String TTipNatur) {
        this.tTipNatur = TTipNatur;
    }
   
                
                @Column(name="T_CORTABLE", nullable=false, precision=2, scale=0)
    public byte getTCortable() {
            return this.tCortable;
    }
    
    public void setTCortable(byte TCortable) {
        this.tCortable = TCortable;
    }
   
                
                @Column(name="T_MEDIDO", nullable=false, length=5)
    public String getTMedido() {
            return this.tMedido;
    }
    
    public void setTMedido(String TMedido) {
        this.tMedido = TMedido;
    }
   
                
                @Column(name="T_TIP_MEDIDOR", nullable=false, length=5)
    public String getTTipMedidor() {
            return this.tTipMedidor;
    }
    
    public void setTTipMedidor(String TTipMedidor) {
        this.tTipMedidor = TTipMedidor;
    }
   
                
                @Column(name="T_TIP_CIIU", nullable=false, length=5)
    public String getTTipCiiu() {
            return this.tTipCiiu;
    }
    
    public void setTTipCiiu(String TTipCiiu) {
        this.tTipCiiu = TTipCiiu;
    }
   
                
                @Column(name="D_EST_SUM", nullable=false, length=5)
    public String getDEstSum() {
            return this.dEstSum;
    }
    
    public void setDEstSum(String DEstSum) {
        this.dEstSum = DEstSum;
    }
   
                
                @Column(name="D_EST_CONTRATO", nullable=false, length=5)
    public String getDEstContrato() {
            return this.dEstContrato;
    }
    
    public void setDEstContrato(String DEstContrato) {
        this.dEstContrato = DEstContrato;
    }
   
                
                @Column(name="D_TARIFA", nullable=false, length=5)
    public String getDTarifa() {
            return this.dTarifa;
    }
    
    public void setDTarifa(String DTarifa) {
        this.dTarifa = DTarifa;
    }
   
                
                @Column(name="D_CALIFICACION", nullable=false, precision=2, scale=0)
    public byte getDCalificacion() {
            return this.dCalificacion;
    }
    
    public void setDCalificacion(byte DCalificacion) {
        this.dCalificacion = DCalificacion;
    }
   
                
                @Column(name="D_RUTA", nullable=false, precision=4, scale=0)
    public short getDRuta() {
            return this.dRuta;
    }
    
    public void setDRuta(short DRuta) {
        this.dRuta = DRuta;
    }
   
                
                @Column(name="D_MARC_MEDIDOR", nullable=false, length=5)
    public String getDMarcMedidor() {
            return this.dMarcMedidor;
    }
    
    public void setDMarcMedidor(String DMarcMedidor) {
        this.dMarcMedidor = DMarcMedidor;
    }
   
                
                @Column(name="D_MULTIFAMILIAR", nullable=false, precision=2, scale=0)
    public byte getDMultifamiliar() {
            return this.dMultifamiliar;
    }
    
    public void setDMultifamiliar(byte DMultifamiliar) {
        this.dMultifamiliar = DMultifamiliar;
    }
   
                
                @Column(name="D_GESTOR", nullable=false, precision=2, scale=0)
    public byte getDGestor() {
            return this.dGestor;
    }
    
    public void setDGestor(byte DGestor) {
        this.dGestor = DGestor;
    }
	
	
	/**
	 * Metodo para obtener el tipo de la clase
	 */
	 @Override
	 @javax.persistence.Transient
	 public Class<?> getClase(){
	 	return Universo.class;
	 }
	 
	 public boolean equals(Object other) {
		if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof Universo) ) return false;
		Universo castOther = ( Universo ) other;
		return (this.getIduniverso()==castOther.getIduniverso());
	}
	
	public int hashCode() {
		int result = 31;
		result = 37 * result + this.getIduniverso();
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		return result;
	}	
		
		
	
 }

